### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by kostasx** [pchan2/Team-Brendan-Pricing-Plan#4]
The Lighthouse Performance index is at 98%. Let's bump it up a bit by compressing all the image through the TinyPNG free online service. 

@alialouies make sure to include the performance gain after the compression (in percentage) in order to have a clear idea of the optimization level.

**Comment by pchan2** [comment]
Hi all, the site is ready to be published at https://pchan2.github.io/Team-Brendan-Pricing-Plan/ using root file as source, but the jpg is missing.

**Comment by alialouies** [comment]
Hey Patrick, 
what do you mean? the images are shown normally to me.

**Comment by pchan2** [comment]
Hi Aliki, thanks for checking the link, good to know you can see the three images, maybe it's just me :-/

**Comment by kostasx** [comment]
Images still not showing on my computer too. @pchan2 @alialouies

**Comment by kostasx** [comment]
![Screen Shot 2020-11-02 at 16 10 02](https://user-images.githubusercontent.com/1638325/97877449-e224f380-1d25-11eb-81fe-3101750b0a7f.jpg)

**Comment by alialouies** [comment]
Yes I just checked the pages and there it's not working it's true.
I'll try to check what it is again

**Comment by alialouies** [comment]
Everything seemed to work again , i did a git pull and a git push also with some new adjustments and all the times i could properly watch the page, but i tried to open the git hub page and the same problem occured :/ any ideas?

**Comment by alialouies** [comment]
![Uploading Screen Shot 2020-11-02 at 15.20.32.png…]()

**Comment by alialouies** [comment]
<img width="298" alt="Screen Shot 2020-11-02 at 15 20 32" src="https://user-images.githubusercontent.com/63586233/97878684-3bd5ef80-1d1f-11eb-8713-7efb9f01b0a0.png">

**Comment by alialouies** [comment]
But here ^^ the images are gone again, while i used the github pages url

**Comment by alialouies** [comment]
ok i got it just give me a sec

**Comment by kostasx** [comment]
Here's the key to solving the mystery: https://youtu.be/T62xj67Mmrk?t=3654

**Comment by alialouies** [comment]
Yes exactly, i did that, but it doesn't seemed to apply for the refreshed git hub page :/

**Comment by kostasx** [comment]
Did you push?

**Comment by alialouies** [comment]
No, it finally did, it just took some time i guess.

**Comment by kostasx** [comment]
Did you do a hard refresh on the browser?

**Comment by alialouies** [comment]
thank you :)

**Comment by kostasx** [comment]
Let's close this Issue. Well done team!

**Comment by pchan2** [comment]
I did some research also and fixed it, thanks for pointing it out.
https://github.community/t/broken-images/10485

________________________________
